apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Production namespace for isolation
namespace: spec-management-prod

# Reference the base configuration
bases:
  - ../../base

# Production-specific labels
commonLabels:
  env: production
  app: spec-management-api

# Production resource configurations
resources:
  - deployment.yaml    # Production deployment with resource limits
  - service.yaml      # Load balancer service configuration
  - ingress.yaml      # TLS-enabled ingress configuration
  - hpa.yaml          # Horizontal Pod Autoscaler configuration

# Container image configuration
images:
  - name: gcr.io/project-id/api
    newTag: latest    # Production image tag

# High availability configuration with multiple replicas
replicas:
  - name: spec-management-api
    count: 2          # Minimum 2 replicas for HA

# Production-specific resource patches
patches: []           # No patches needed currently, but section available for future use