# Alertmanager configuration v0.25.0
# Handles alert routing, grouping and notifications for the specification management API system

global:
  # Time to wait before marking an alert as resolved
  resolve_timeout: 5m

  # SMTP configuration for email notifications
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: alertmanager@spec-api.com
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_require_tls: true

  # PagerDuty configuration for critical alerts
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  pagerduty_service_key: ${PAGERDUTY_KEY}

# Load notification templates
templates:
  - templates/*.tmpl

# Root route configuration
route:
  # Group alerts by name and service
  group_by: ['alertname', 'service']
  
  # Initial wait time before sending grouped alert
  group_wait: 30s
  
  # Minimum time between sending two alerts from the same group
  group_interval: 5m
  
  # Minimum time before re-sending an alert
  repeat_interval: 4h
  
  # Default receiver if no routes match
  receiver: email-notifications

  # Specific routing configurations
  routes:
    # Route for critical severity alerts
    - match:
        severity: critical
      receiver: pagerduty-critical
      # Send critical alerts immediately
      group_wait: 0s
      # Re-notify every hour for critical alerts
      repeat_interval: 1h

# Notification receivers configuration
receivers:
  # Email notifications for standard alerts
  - name: email-notifications
    email_configs:
      - to: team@spec-api.com
        send_resolved: true
        require_tls: true
        html: '{{ template "email.html" . }}'

  # PagerDuty notifications for critical alerts
  - name: pagerduty-critical
    pagerduty_configs:
      - service_key: ${PAGERDUTY_KEY}
        send_resolved: true
        description: '{{ template "pagerduty.description" . }}'

# Alert inhibition rules
inhibit_rules:
  # Suppress warning alerts if there is a critical alert for the same alertname/service
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname', 'service']

# Muting and time intervals can be added here if needed
# mute_time_intervals:
#   - name: maintenance-window
#     time_intervals:
#       - times:
#           - start_time: '00:00'
#             end_time: '04:00'
#         weekdays: ['saturday', 'sunday']