apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: spec-management-api
    component: configuration
    managed-by: kustomize
type: Opaque
stringData:
  # PostgreSQL Configuration
  # Version: PostgreSQL 14+
  POSTGRES_USER: db_user
  POSTGRES_PASSWORD: db_password
  POSTGRES_DB: spec_management
  POSTGRES_HOST: cloudsql-proxy
  POSTGRES_PORT: "5432"

  # Google OAuth2.0 Authentication
  # Version: Google Cloud User Store
  GOOGLE_CLIENT_ID: google_oauth_client_id
  GOOGLE_CLIENT_SECRET: google_oauth_client_secret

  # JWT Configuration
  # Algorithm: HS256
  JWT_SECRET_KEY: jwt_signing_key
  JWT_EXPIRY_HOURS: "24"

  # Redis Cache Configuration
  # Version: Redis 6+
  REDIS_PASSWORD: redis_auth_password
  REDIS_HOST: redis-master
  REDIS_PORT: "6379"
  REDIS_SSL_ENABLED: "true"

  # Rate Limiting Configuration
  RATE_LIMIT_PER_HOUR: "1000"