# Kubernetes ServiceAccount API version v1.24+
apiVersion: v1
kind: ServiceAccount

metadata:
  name: spec-management-api
  labels:
    app: spec-management-api
    managed-by: kustomize
    environment: production
    component: api
    security-tier: restricted
  annotations:
    # Enable strict secret mounting controls
    kubernetes.io/enforce-mountable-secrets: "true"
    # Enable GCP Workload Identity integration
    cloud.google.com/workload-identity: "true"
    # Bind to GCP service account
    iam.gke.io/gcp-service-account: spec-mgmt-api@project-id.iam.gserviceaccount.com
    # Enable workload certificate-based authentication
    security.cloud.google.com/use-workload-certificates: "true"
    # Enable graceful pod termination handling
    container.googleapis.com/instance-termination-handler: "true"

# Enable automatic token mounting for pod authentication
automountServiceAccountToken: true

# Define allowed secrets that can be mounted
secrets:
  - name: spec-management-api-secrets